version: '3'
  
networks:
  ft_transcendence:
    driver: bridge

services: 
  nginx:
    container_name: nginx
    volumes: 
      - ./pong:/etc/frontend
    build: ./pong
    networks:
      - ft_transcendence
    ports:
      - "443:443"
  postgresql:
    container_name: postgresql
    build: ./backend/database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ft_transcendence

    #django:
    #  container_name: django
    #volumes: 
    #  - django_vol:/var/www/html
    #build: ./pong
    #networks:
    #  - inception
    #ports:
    #  - "8000"

volumes:
  nginx_vol:
#  django_vol: