version: '3'
  
networks:
  transcendance:
    driver: bridge

services: 

  django:
    container_name: django
    volumes: 
      - ./backend:/code
      - static:/static
    build: ./backend
    networks:
      - transcendance
    ports:
      - 8000:8000
      - 8001:8001
    env_file:
      - .env

  nginx:
    container_name: nginx
    volumes: 
      - static:/static
    build: ./nginx
    networks:
      - transcendance
    ports:
      - "443:443"
    depends_on:
      - django


volumes:
  static:

