version: '3'
  
networks:
  inception:
    driver: bridge

services: 
  nginx:
    container_name: nginx
    volumes: 
      - wordpress_vol:/var/www/html
    build: ./requirement/nginx
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: unless-stopped

volumes:
  nginx_vol:
    driver_opts:
      o: bind
      device: ./volume/nginx
      type: none