version: '3'
  
networks:
  inception:
    driver: bridge

services: 
  nginx:
    container_name: nginx
    volumes: 
      - nginx_vol:/var/www/html
    build: ./pong
    networks:
      - inception
    ports:
      - "443:443"

volumes:
  nginx_vol: