version: '3'
  
networks:
  transcendance:
    driver: bridge

services: 

  django:
    container_name: django
    volumes: 
      - ./backend:/code
      - ./backend/transcendence/static/:/static/
    build: ./backend
    command: /code/entrypoint.sh
    networks:
      - transcendance
    ports:
      - 8000:8000
      - 8001:8001
    env_file:
      - .env
    depends_on:
      - database

  nginx:
    container_name: nginx
    volumes: 
      - ./backend/transcendence/static/:/static/
    build: ./nginx
    networks:
      - transcendance
    ports:
      - "443:443"
    depends_on:
      - django

  database:
    container_name: database
    build: ./backend/database
    networks:
      - transcendance
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  static:
  db_data:

