version: '3'
  
networks:
  inception:
    driver: bridge

services: 
  nginx:
    container_name: nginx
    volumes: 
      - nginx_vol:/var/www/html
    build: ./pong
    networks:
      - inception
    ports:
      - "443:443"

    #django:
    #  container_name: django
    #volumes: 
    #  - django_vol:/var/www/html
    #build: ./pong
    #networks:
    #  - inception
    #ports:
    #  - "8000"

volumes:
  nginx_vol:
  django_vol: