# Use an official Python runtime as a base image
FROM python:3.10

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

# Copy the dependencies file to the working directory
COPY requirements.txt /code/

# Install dependencies
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /code
COPY . /code/

# Expose the port that Daphne will run on
EXPOSE 8001
EXPOSE 8000
# Command to run Daphne
CMD python manage.py migrate && daphne backend.asgi:application --bind 0.0.0.0 --port 8000