# Use an official Python runtime as a base image
FROM python:3.10

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

COPY . /code/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
# Expose the port that Daphne will run on
EXPOSE 8001
EXPOSE 8000
#distribute the file
RUN python manage.py collectstatic --noinput
# Command to run Daphne
CMD python manage.py makemigrations && python manage.py migrate && daphne backend.asgi:application --bind 0.0.0.0 --port 8000