# Generated by Django 5.0.6 on 2024-07-04 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('hashed_password', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PongStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pong.user')),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('paddle_hits', models.IntegerField(default=0)),
                ('ball_travel_distance', models.IntegerField(default=0)),
                ('online_game_played', models.IntegerField(default=0)),
                ('offline_game_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UpStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pong.user')),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('games_drawn', models.IntegerField(default=0)),
                ('jump_count', models.IntegerField(default=0)),
                ('travelled_distance', models.IntegerField(default=0)),
                ('online_game_played', models.IntegerField(default=0)),
                ('offline_game_played', models.IntegerField(default=0)),
            ],
        ),
    ]
