# Generated by Django 5.0.6 on 2024-07-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pongstats',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='upstats',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
