# Generated by Django 5.0.6 on 2024-07-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_pongstats_options_alter_upstats_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pongstats',
            table='pong_stats',
        ),
        migrations.AlterModelTable(
            name='upstats',
            table='up_stats',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
