FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

COPY conf/default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/ssl

RUN chmod 777 /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj "/C=CA/ST=QC/L=QC/O=42/CN=localhost" -sha256

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
